name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - uses: syphar/restore-virtualenv@v1.2
        id: venv
        with:
          requirement_files: requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.venv.outputs.cache-hit != 'true'

      - run: pip install -r Code/requirements.txt
        if: steps.venv.outputs.chache-hit != 'true'

      - name: Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint;
          pylint *.py
  
  pep8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8; flake8 *.py
